# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20a9f9906ad57c8379dee8abd72a5ae82ab6094ec1ab226c574032acd56ccfea690813b4646ea87405c58f5ccc790a8f6d5ab3ef7effa8ed9c4060d3937c150b

test:
  secret_key_base: 982aa20060b7163a5da6a5a0e6981918872dcfbd3159d8c4b80e5c16f90888908524c11003e8e440c21c695eaa9e556ffe596f1cda7cfdda63f5f04bcb555d80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
